import { RecordProps } from './record-types';

export const apiListFixture: RecordProps[] = [
  {
    id: 'fixture-segment',
    name: 'Segment',
    slug: 'segment',
    description:
      'Segment is a cross-platform data collection and analytics software that supports APIs. It also supports React Native.',
    website_url: 'https://segment.com/',
    type: ['Analytics'],
  },
  {
    id: 'fixture-realm',
    name: 'realm',
    slug: 'realm',
    description:
      'The Realm React Native SDK allows you to use Realm Database and backend Apps from React Native.',
    platform: ['Android', 'iOS'],
    pricing: ['Open source'],
    website_url: 'https://realm.io/',
    type: ['Database & Storage'],
  },
  {
    id: 'fixture-mixpanel',
    name: 'Mixpanel',
    slug: 'mixpanel',
    description:
      'Mixpanel allows you to segment and creates funnels to analyze user actions. It also displays data regarding data points such as location, device, channels, and more.',
    features: ['Push notifications', 'A/B testing'],
    website_url: 'https://mixpanel.com/',
    type: ['Analytics'],
  },
  {
    id: 'fixture-uxcam',
    name: 'UXCam',
    slug: 'uxcam',
    features: ['Analytics'],
    pricing: ['Free tier', 'Premium tiers'],
    website_url: 'https://uxcam.com/',
    type: ['Analytics'],
  },
  {
    id: 'fixture-watermelondb',
    name: 'Watermelon DB',
    slug: 'watermelon-db',
    description:
      'Build powerful React and React Native apps that scale from hundreds to tens of thousands of records and remain fast.',
    pricing: ['Open source'],
    website_url: 'https://watermelondb.dev/',
    type: ['Database & Storage'],
  },
  {
    id: 'fixture-expo',
    name: 'Expo',
    slug: 'expo',
    description:
      'An open-source platform for making universal native apps with React. Expo runs on Android, iOS, and the web.',
    pricing: ['Open source'],
    website_url: 'https://expo.dev/',
    type: ['CI/CD & Release'],
  },
  {
    id: 'fixture-amplify',
    name: 'Amplify',
    slug: 'amplify',
    pricing: ['Free tier', 'Pay as-you-go'],
    website_url: 'https://docs.amplify.aws/react-native/',
    type: ['CI/CD & Release', 'Backend & APIs', 'Auth & Identity'],
  },
  {
    id: 'fixture-fusionauth',
    name: 'FusionAuth',
    slug: 'fusionauth',
    description:
      'FusionAuth is an open source identity and access management platform.',
    pricing: ['Free tier', 'Premium tiers'],
    website_url: 'https://fusionauth.io/',
    type: ['Auth & Identity'],
  },
  {
    id: 'fixture-sentry',
    name: 'Sentry',
    slug: 'sentry',
    description: 'Application Monitoring and Error Tracking Software.',
    features: ['Crash reporting'],
    platform: ['Android', 'iOS', 'Web'],
    pricing: ['Free tier', 'Premium tiers'],
    website_url: 'https://sentry.io',
    type: ['Error Monitoring'],
  },
  {
    id: 'fixture-firebase',
    name: 'Firebase',
    slug: 'firebase',
    description: 'Multiple features in one product — backed by Google.',
    features: [
      'Hosting',
      'Crash reporting',
      'Remote config',
      'Cloud messaging',
      'Real-time database',
      'Analytics',
    ],
    platform: ['Android', 'iOS', 'Unity', 'Web'],
    pricing: ['Free tier', 'Pay as-you-go'],
    website_url: 'https://rnfirebase.io',
    type: ['CI/CD & Release', 'Backend & APIs', 'Database & Storage'],
  },
  {
    id: 'fixture-stream',
    name: 'Stream',
    slug: 'stream',
    description:
      'Stream is the #1 chat-messaging and activity feed platform — it handles all of the complexity of building chat apps for you.',
    features: ['Push notifications', 'Video', 'Image & file upload'],
    website_url: 'https://getstream.io/',
    type: ['Backend & APIs'],
  },
  {
    id: 'fixture-mmkv',
    name: 'React Native MMKV',
    slug: 'react-native-mmkv',
    description:
      'The fastest key/value storage for React Native. ~30x faster than AsyncStorage!',
    platform: ['Android', 'iOS'],
    pricing: ['Open source'],
    website_url: 'https://github.com/mrousavy/react-native-mmkv',
    type: ['Database & Storage'],
  },
  {
    id: 'fixture-pouchdb',
    name: 'PouchDB',
    slug: 'pouchdb',
    description:
      'PouchDB is an open-source JavaScript database that allows apps to save data locally while offline, then synchronize it with CouchDB and other compatible servers once the app is back online.',
    pricing: ['Open source'],
    website_url: 'https://pouchdb.com/',
    type: ['Database & Storage'],
  },
];
