// Extracts the SVG path + brand color of every icon referenced in
// src/data/catalog.ts from @icons-pack/react-simple-icons, so the UI and the
// server-rendered share image draw from the same static data.
//
// Usage: node apps/9frameworks/scripts/generate-icons.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const appRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
);
const iconsDir = path.join(
  path.dirname(require.resolve('@icons-pack/react-simple-icons/package.json')),
  'icons',
);

const catalog = readFileSync(path.join(appRoot, 'src/data/catalog.ts'), 'utf8');
const names = [
  ...new Set([...catalog.matchAll(/icon: '(\w+)'/g)].map((m) => m[1])),
].sort();

const icons = {};
for (const name of names) {
  const source = readFileSync(path.join(iconsDir, `Si${name}.mjs`), 'utf8');
  const hex = source.match(/defaultColor = "(#[0-9A-Fa-f]{6})"/)?.[1];
  const paths = [...source.matchAll(/"path", \{ d: "([^"]+)"/g)].map(
    (m) => m[1],
  );
  if (!hex || paths.length !== 1) {
    throw new Error(`Unexpected icon format for Si${name}`);
  }
  icons[name] = { hex, path: paths[0] };
}

const output = `// Generated by scripts/generate-icons.mjs — do not edit by hand.
// Icon data from Simple Icons (CC0-1.0), https://simpleicons.org
import type { IconData } from './catalog';

export const ICONS: Record<string, IconData> = ${JSON.stringify(icons, null, 2)};
`;

writeFileSync(path.join(appRoot, 'src/data/icons.generated.ts'), output);
console.log(`Wrote ${names.length} icons`);
