#!/usr/bin/env python3
"""Extracts Space Grotesk Bold outlines for the showreel title.

The lockup draws each letter contour by contour, so it needs real glyph paths
rather than live text. Writes glyphs.js next to this file.

Usage: python3 tools/podcast-motion/build-glyphs.py
"""
import io
import json
import pathlib
import re
import urllib.request

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

TEXT = "Le Cross Platform Show"
SIZE = 150  # px, must match TITLE_SIZE in showreel.html

# An old user agent makes Google Fonts serve a static TTF instead of woff2.
request = urllib.request.Request(
    "https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@700",
    headers={"User-Agent": "Mozilla/4.0"},
)
css = urllib.request.urlopen(request).read().decode()
ttf_url = re.search(r"url\((\S+?\.ttf)\)", css).group(1)
font = TTFont(io.BytesIO(urllib.request.urlopen(ttf_url).read()))

glyph_set = font.getGlyphSet()
cmap = font.getBestCmap()
scale = SIZE / font["head"].unitsPerEm

glyphs = {}
for char in sorted(set(TEXT) - {" "}):
    name = cmap[ord(char)]
    pen = SVGPathPen(glyph_set, ntos=lambda v: f"{v:.2f}".rstrip("0").rstrip("."))
    # Font units are y-up; flip to screen space with the baseline at y = 0.
    glyph_set[name].draw(TransformPen(pen, (scale, 0, 0, -scale, 0, 0)))
    contours = [f"M{c.strip()}" for c in pen.getCommands().split("M") if c.strip()]
    glyphs[char] = {"adv": round(font["hmtx"][name][0] * scale, 2), "contours": contours}

os2 = font["OS/2"]
data = {
    "size": SIZE,
    "cap": round(os2.sCapHeight * scale, 2),
    "xHeight": round(os2.sxHeight * scale, 2),
    "glyphs": glyphs,
}
out = pathlib.Path(__file__).with_name("glyphs.js")
out.write_text(f"// Generated by build-glyphs.py — do not edit.\nwindow.GLYPHS = {json.dumps(data)};\n")
print(f"wrote {out} ({len(glyphs)} glyphs)")
