name: Run tests

on: [push, pull_request]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # if needed
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command
          
      - name: Test the app
        uses: borales/actions-yarn@v4
        with:
          cmd: weshipit:test # will run `yarn test` command

      - name: Run test in UI
        uses: borales/actions-yarn@v4
        with:
          cmd: ui:test
